services:
  proxy-sub-transformer-rust:
    restart: unless-stopped
    image: dev2people/proxy-sub-transformer-rust:latest
    ports:
      - "18189:8189"
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - DATABASE_URL=sqlite:///app/data/sub.db?mode=rwc
      - RUST_LOG=info
      - JS_TEMPLATE_DIR=./config/js_templates
      - API_AUTH_KEY=epYeobK02c6ee9ELuCkPAplZYyqAjOJN
    depends_on:
      - clashsub-tools-clashspeedtest

  clashsub-tools-clashspeedtest:
    restart: unless-stopped
    image: dev2people/clashsub-tools-clashspeedtest-v0
    container_name: clash-speedtest
    networks:
      default:
        aliases:
          - clash-speedtest
    ports:
      - "57890:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - AUTH_KEY=epYeobK02c6ee9ELuCkPAplZYyqAjOJN